spring.application.name=fullstackweb
spring.datasource.url=jdbc:mysql://root:AgCeldZCdibjDrrxhrQqRoPGfhHtpMow@mysql.railway.internal:3306/railway
spring.datasource.username=root
server.port=8080
spring.datasource.password=AgCeldZCdibjDrrxhrQqRoPGfhHtpMow
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=create
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Static Resources
spring.web.resources.static-locations=classpath:/images/
spring.mvc.static-path-pattern=/images/**
