-- phpMyAdmin SQL Dump
-- version 5.2.1
-- https://www.phpmyadmin.net/
--
-- Máy chủ: 127.0.0.1
-- Thời gian đã tạo: Th5 28, 2025 lúc 12:23 PM
-- Phiên bản máy phục vụ: 8.0.37
-- Phiên bản PHP: 8.2.12

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Cơ sở dữ liệu: `bakerystore`
--

-- --------------------------------------------------------

--
-- Cấu trúc bảng cho bảng `product`
--

CREATE TABLE `product` (
  `id` int NOT NULL,
  `name` varchar(255) DEFAULT NULL,
  `price` int DEFAULT NULL,
  `flavor` varchar(255) DEFAULT NULL,
  `structure` varchar(255) DEFAULT NULL,
  `decorate` varchar(255) DEFAULT NULL,
  `preserve` varchar(255) DEFAULT NULL,
  `detail` text CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci,
  `image` varchar(255) DEFAULT NULL,
  `category_id` int NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

--
-- Đang đổ dữ liệu cho bảng `product`
--

INSERT INTO `product` (`id`, `name`, `price`, `flavor`, `structure`, `decorate`, `preserve`, `detail`, `image`, `category_id`) VALUES
(1, 'SWEETBOX LOVE – Hộp 8 vị', 295000, 'Ngọt dịu – Béo nhẹ – Chua ngọt – Thơm tự nhiên.', 'Lớp trang trí trái cây tươi, sô-cô-la hoặc jelly,…\r\nMousse theo từng vị bánh.\r\nCốt bánh bông lan.', NULL, 'Bánh nên được dùng trong ngày và ngon hơn khi bảo quản lạnh trước khi thưởng thức.', 'Sweetbox Love chính là lời chúc Valentine ý nghĩa mà Cái Lò Nướng dành riêng cho mùa yêu. Từng chi tiết, từ sắc hồng dịu dàng đến lớp ép kim tinh tế, đều thể hiện sự chăm chút và tinh thần lãng mạn của ngày lễ tình nhân.\r\nBên trong, 16 hương vị mousse không chỉ là món tráng miệng, mà còn là “cái cớ” để cả hai ngồi lại, chia sẻ những câu chuyện nhỏ trong ngày và cảm nhận sự hiện diện đầy ý nghĩa của nhau. Mỗi hương vị, mỗi câu chuyện… sẽ biến một buổi tối bình thường thành một kỷ niệm Valentine thật đáng nhớ.\r\n3 lựa chọn Sweetbox Love dành cho bạn mùa Valentine này:\r\nSet 8 bánh: Khế (vị mới), Cherry, Bơ, Bắp, Chuối Caramel, Mãng Cầu, Trà Xanh, Ổi Hồng.\r\nSet 12 bánh: Măng Cụt (vị mới), Cherry, Bơ, Bắp, Táo, Yuzu (Sữa Chua Phô Mai), Xoài, Lê Hoa Cúc, Dưa Lưới, Dừa, Trà Xanh, Ổi Hồng.\r\nSet 16 bánh: Măng Cụt, Khế, Cherry, Bơ, Bắp, Táo, Yuzu (Sữa Chua Phô Mai), Xoài, Lê Hoa Cúc, Chuối Caramel, Mãng Cầu, Dưa Lưới, Vải Hoa Hồng, Dừa, Trà Xanh, Ổi Hồng.\r\nValentine này, không cần phải rình rang. Chỉ cần một hộp Sweetbox Love, và nhiều thời gian bên nhau – thế là đủ cho một mùa yêu thật dịu dàng.', 'sweetBoxLove.jpg', 1),
(2, 'Matcha Chocolate Cake', 175000, 'Ngọt dịu – đậm vị matcha.', 'Bánh gồm 5 lớp (từ dưới lên trên):\r\n\r\n+ Bạt bánh matcha cake nướng.\r\n\r\n+ Mousse matcha socola nguyên chất.\r\n\r\n+ Lớp ganache dẻo socola matcha.\r\n\r\n+ Lớp socola matcha nguyên chất.\r\n\r\n+ Bột matcha.', NULL, 'Bánh nên được dùng trong ngày và ngon hơn khi bảo quản lạnh trước khi thưởng thức.', 'Matcha Chocolate Cake tại Cái Lò Nướng có gì đặc biệt?\r\nĐó là kết cấu 5 tầng độc đáo gồm:\r\n\r\nLớp bạt bánh matcha mềm mịn kết hợp với lớp mousse chocolate thanh mát, tan chảy nơi đầu lưỡi.\r\nLớp ganache matcha dẻo mịn, cân bằng vị đắng dịu của trà xanh và ngọt ngào của chocolate trắng.\r\nLớp phủ chocolate giòn tan phía trên, mang lại cảm giác thú vị khi chiếc muỗng “đập” xuống, hòa cùng lớp bột matcha nguyên chất tạo nên một dư vị đậm đà và cuốn hút.\r\nSự đan xen giữa các tầng kết cấu mềm – dẻo – giòn, vị đắng dịu của matcha và vị ngọt nhẹ nhàng của chocolate khiến mỗi muỗng bánh trở thành một trải nghiệm thư giãn, giúp bạn tận hưởng trọn vẹn những khoảnh khắc đặc biệt.', 'matchaChocolateCake.jpg', 2),
(3, 'Tropical Vibes Mousse – Mousse Ổi hồng & Chanh dây', 485000, 'Chua thanh – Ngọt tự nhiên – Thơm nhẹ.', 'Phần thân bánh gồm các lớp chính:\r\n\r\n+ Mousse ổi xá lị, phúc bồn tử, sô-cô-la.\r\n\r\n+ Nhân ổi xá lị.\r\n\r\n+ Bông lan vị vani.\r\n\r\n+ Nhân chanh dây.', 'Dâu tươi, jelly, búp kem, sô-cô-la.', 'Bánh nên được dùng trong ngày và ngon hơn khi bảo quản lạnh trước khi thưởng thức.', 'Bánh Mousse Ổi hồng & Chanh dây được Cái Lò Nướng lấy cảm hứng từ trái ổi xá lị – loại trái có nhiều nước, ít đường, ít hạt, ít tinh bột, vốn dĩ đã rất thích hợp dùng trong chế biến bánh ngọt. Cùng kết hợp với phúc bồn tử và sô-cô-la trắng đã tạo nên lớp mousse cân bằng về độ chua ngọt. \r\n\r\nBánh Mousse Ổi hồng & Chanh dây có hai lớp nhân được chế biến thủ công để giữ hương vị trái cây nguyên bản. Với lớp nhân từ quả ổi xá lị thì thịt ổi được cắt hạt lựu nên khi nhai cho cảm giác sần sật còn lớp nhân chanh dây mềm tươi mát. \r\n\r\nBánh Mousse Ổi hồng & Chanh dây đang là mẫu bánh mousse có nhiều lớp nhất tại Cái Lò Nướng.', 'tropicalVibesMousse.jpg', 3),
(4, 'Chéri Lady – Entremet Cherry', 595000, 'Ngọt dịu – Chua thanh – Thơm tự nhiên – Béo nhẹ.', 'Phần thân bánh gồm các lớp chính:\r\n\r\n+ Mousse cherry.\r\n\r\n+ Nhân cherry và rượu cherry.\r\n\r\n+ Nhân sô-cô-la tươi vị matcha.\r\n\r\n+ Bông lan vị vani.', 'Quả mâm xôi, jelly, sô-cô-la trắng phun xù, tráng gương.', 'Bánh nên được dùng trong ngày và ngon hơn khi bảo quản lạnh trước khi thưởng thức.', 'Entremet Cherry là mẫu bánh có thành phần cấu trúc hết sức cầu kỳ với nhiều tầng nhân được làm thủ công hết sức công phu. Bánh vừa có vị ngọt dịu vừa có vị chua thanh và hương thơm tự nhiên tinh tế.\r\n\r\nTrái cherry nhập khẩu cao cấp kết hợp sữa chua tạo thành lớp mousse đặc biệt mới lạ. Bánh có hai lớp nhân được làm từ cherry tươi kết hợp với một chút rượu cherry, lớp nhân còn lại có nguyên liệu chính từ sô-cô-la tươi vị matcha từ Nhật Bản và sô-cô-la trắng nguyên chất 40%. Lớp nhân sô-cô-la rất mềm dẻo và mang đậm hương vị matcha.\r\n\r\nĐể bánh cốt bánh bông lan vị vani là thành phần không thể thiếu để bánh luôn được thưởng thức trọn vẹn. Tại Cái Lò Nướng, bánh bông lan luôn mềm xốp và ngon lành. \r\n\r\nBánh Entremet Cherry là mẫu bánh có lớp trang trí cầu kỳ trong dòng bánh này, vì đây là sự kết hợp giữa kỹ thuật tráng gương và phun xù để làm cho bánh được bắt mắt và hấp dẫn hơn.', 'cheriLady.jpg', 4),
(5, 'Delicate Bloom – Bánh Kem Bắp Dâu', 465000, 'Ngọt dịu – Thơm đặc trưng – Béo nhẹ.', 'Phần thân bánh gồm các lớp chính:\r\n\r\n+ Mousse bắp.\r\n\r\n+ Bông lan bắp.', 'nho, dâu, đào, bắp.', 'Bánh nên được dùng trong ngày và ngon hơn khi bảo quản lạnh trước khi thưởng thức.', 'Delicate Bloom không chỉ là một phiên bản mới mẻ của hương vị bắp truyền thống mà còn là nỗ lực của Cái Lò Nướng trong việc không ngừng đổi mới sáng tạo, mang đến sức sống mới cho những vị bánh đã trở thành biểu tượng quen thuộc với khách hàng lâu năm. Bánh Kem Bắp Dâu mới với tạo hình đóa hoa nở rộ – “bloom” đem tới màu sắc rực rỡ của những ngày cuối xuân đầu hè ấm áp, tổng hòa của những hương vị thân quen, gần gũi.\r\n\r\nTạo hình bánh độc đáo với cánh hoa được tạo thành từ các loại trái cây như dâu, đào, bắp và nho.\r\nPhần mousse thơm ngon và bông lan êm dịu đều được làm từ những hạt bắp căng tròn tạo nên một hương vị đặc biệt và độc đáo.\r\nVới sự đổi mới trong trang trí, chúng mình muốn mang lại cho khách hàng trải nghiệm tốt nhất mỗi khi đặt bánh, mỗi chiếc bánh vượt qua kỳ vọng của bạn.\r\n\r\nBạn hãy đến và thưởng thức ngay Delicate Bloom vì đó là một sự kết hợp hoàn hảo giữa hương vị truyền thống và nghệ thuật sáng tạo hiện đại!', 'delicateBloom.jpg', 5),
(6, 'Flan Gato Berry Mix', 515000, 'Ngọt dịu – Béo nhẹ – Thơm – Đắng nhẹ.', 'Phần thân bánh gồm các lớp chính:\r\n\r\n+ Bánh flan vị truyền thống.\r\n\r\n+ Bông lan sô-cô-la.', 'jelly caramel, dâu tươi, việt quất.', 'Bánh nên được dùng trong ngày và ngon hơn khi bảo quản lạnh trước khi thưởng thức.', 'Flan Gato là dòng bánh mà Cái Lò Nướng chiếm ưu thế về sản lượng cung cấp cho thị trường Hồ Chí Minh. Bánh có hương vị ngon lành nên người dùng ở mọi lứa tuổi đều yêu thích.\r\n\r\nBánh có hai lớp chính, đó là flan truyền thống ngọt ngào mềm, căng mịn và bông lan sô-cô-la có vị đắng nhẹ tinh tế. Hai lớp bánh với hai hương vị khác nhau nhưng khi kết hợp tạo nên một chiếc bánh ngon nịnh vị và khi dùng thực khách không có cảm giác ngán.\r\n\r\nFlan Gato Berry Mix là mẫu bánh có phần trang trí từ dâu tươi và việt quất tươi mát nằm bên trên lớp jelly caramel. Một phụ kiện không thể thiếu trên chiếc bánh kem mà đặc biệt cực kỳ phù hợp với Flan Gato đó là bộ sưu tập cây ghim với nhiều chủ đề khác nhau.', 'flanGatoBerryMix.png', 6),
(7, 'Fruits and Nuts Biscotti – Biscotti trái cây và hạt', 59000, NULL, 'Hạnh nhân, hạt điều, nho khô, mứt hoa atiso, nam việt quất, lòng trắng, đường cát, bột mì.', NULL, NULL, 'Đánh dấu sự trở lại “NƠI TÌNH YÊU BẮT ĐẦU” và dịp “ra mắt” của cửa hàng Cái Lò Nướng tại Thủ Đức. Chúng mình đã mang đến món quà đặc biệt đến Fan của Cái Lò Nướng:\r\n\r\n6 Loại bánh khô với hương vị độc đáo, hứa hẹn làm hài lòng mọi khẩu vị.\r\n– Cookie rong biển hạt: Sự kết hợp hài hòa giữa rong biển, các loại hạt dinh dưỡng và vị ngọt thanh của cookie, mang đến trải nghiệm hoàn toàn mới.\r\n– Cookie chanh dây: Vị chua ngọt của chanh dây quyện cùng bánh quy bơ, tạo nên hương vị khó quên.\r\n– Cookie chà bông cay: Vị mặn mặn, cay cay kích thích cùng vị ngọt nhẹ của bánh quy, níu giữ bạn ngay từ miếng đầu tiên.\r\n– Cookie kem phô mai: Vị ngọt, béo, mặn hài hòa quyện cùng vị phô mai thơm lừng, mang đến trải nghiệm vị giác khó quên.\r\n– Biscotti Trái Cây và Hạt: Sự kết hợp độc đáo giữa nho khô, atiso và hạnh nhân mang đến hương vị thơm ngon, bổ dưỡng.\r\n– Snack rong biển: Vị giòn tan, đậm đà của rong biển hoà cùng vị mặn ngọt rất “cuốn” nhờ nước sốt tự nấu, kích thích vị giác.\r\nTất cả các loại bánh mới này đều được làm từ những nguyên liệu lành mạnh thân thiện với sức khỏe của bạn. Mỗi hộp bánh đều là món quà vặt nhâm nhi của bạn cùng những người thân yêu.', 'fruitsAndNutsBiscotti.jpg', 7),
(8, 'Bánh Mì Kem Phô mai Nam Việt Quất', 27000, NULL, NULL, NULL, NULL, 'Bánh Mì Kem Phô mai Nam Việt Quất: Bánh mì mềm, nhân phô mai và mứt nam việt quất.', 'banhMiKemPhoMaiVietQuat.jpg', 8),
(9, 'SWEETBOX LOVE – Hộp 8 vị', 295000, 'Ngọt dịu – Béo nhẹ – Chua ngọt – Thơm tự nhiên.', 'Lớp trang trí trái cây tươi, sô-cô-la hoặc jelly,…\r\nMousse theo từng vị bánh.\r\nCốt bánh bông lan.', NULL, 'Bánh nên được dùng trong ngày và ngon hơn khi bảo quản lạnh trước khi thưởng thức.', 'Sweetbox Love chính là lời chúc Valentine ý nghĩa mà Cái Lò Nướng dành riêng cho mùa yêu. Từng chi tiết, từ sắc hồng dịu dàng đến lớp ép kim tinh tế, đều thể hiện sự chăm chút và tinh thần lãng mạn của ngày lễ tình nhân.\r\nBên trong, 16 hương vị mousse không chỉ là món tráng miệng, mà còn là “cái cớ” để cả hai ngồi lại, chia sẻ những câu chuyện nhỏ trong ngày và cảm nhận sự hiện diện đầy ý nghĩa của nhau. Mỗi hương vị, mỗi câu chuyện… sẽ biến một buổi tối bình thường thành một kỷ niệm Valentine thật đáng nhớ.\r\n3 lựa chọn Sweetbox Love dành cho bạn mùa Valentine này:\r\nSet 8 bánh: Khế (vị mới), Cherry, Bơ, Bắp, Chuối Caramel, Mãng Cầu, Trà Xanh, Ổi Hồng.\r\nSet 12 bánh: Măng Cụt (vị mới), Cherry, Bơ, Bắp, Táo, Yuzu (Sữa Chua Phô Mai), Xoài, Lê Hoa Cúc, Dưa Lưới, Dừa, Trà Xanh, Ổi Hồng.\r\nSet 16 bánh: Măng Cụt, Khế, Cherry, Bơ, Bắp, Táo, Yuzu (Sữa Chua Phô Mai), Xoài, Lê Hoa Cúc, Chuối Caramel, Mãng Cầu, Dưa Lưới, Vải Hoa Hồng, Dừa, Trà Xanh, Ổi Hồng.\r\nValentine này, không cần phải rình rang. Chỉ cần một hộp Sweetbox Love, và nhiều thời gian bên nhau – thế là đủ cho một mùa yêu thật dịu dàng.', 'sweetBoxLove.jpg', 1),
(10, 'Matcha Chocolate Cake', 175000, 'Ngọt dịu – đậm vị matcha.', 'Bánh gồm 5 lớp (từ dưới lên trên):\r\n\r\n+ Bạt bánh matcha cake nướng.\r\n\r\n+ Mousse matcha socola nguyên chất.\r\n\r\n+ Lớp ganache dẻo socola matcha.\r\n\r\n+ Lớp socola matcha nguyên chất.\r\n\r\n+ Bột matcha.', NULL, 'Bánh nên được dùng trong ngày và ngon hơn khi bảo quản lạnh trước khi thưởng thức.', 'Matcha Chocolate Cake tại Cái Lò Nướng có gì đặc biệt?\r\nĐó là kết cấu 5 tầng độc đáo gồm:\r\n\r\nLớp bạt bánh matcha mềm mịn kết hợp với lớp mousse chocolate thanh mát, tan chảy nơi đầu lưỡi.\r\nLớp ganache matcha dẻo mịn, cân bằng vị đắng dịu của trà xanh và ngọt ngào của chocolate trắng.\r\nLớp phủ chocolate giòn tan phía trên, mang lại cảm giác thú vị khi chiếc muỗng “đập” xuống, hòa cùng lớp bột matcha nguyên chất tạo nên một dư vị đậm đà và cuốn hút.\r\nSự đan xen giữa các tầng kết cấu mềm – dẻo – giòn, vị đắng dịu của matcha và vị ngọt nhẹ nhàng của chocolate khiến mỗi muỗng bánh trở thành một trải nghiệm thư giãn, giúp bạn tận hưởng trọn vẹn những khoảnh khắc đặc biệt.', 'matchaChocolateCake.jpg', 2),
(11, 'Tropical Vibes Mousse – Mousse Ổi hồng & Chanh dây', 485000, 'Chua thanh – Ngọt tự nhiên – Thơm nhẹ.', 'Phần thân bánh gồm các lớp chính:\r\n\r\n+ Mousse ổi xá lị, phúc bồn tử, sô-cô-la.\r\n\r\n+ Nhân ổi xá lị.\r\n\r\n+ Bông lan vị vani.\r\n\r\n+ Nhân chanh dây.', 'Dâu tươi, jelly, búp kem, sô-cô-la.', 'Bánh nên được dùng trong ngày và ngon hơn khi bảo quản lạnh trước khi thưởng thức.', 'Bánh Mousse Ổi hồng & Chanh dây được Cái Lò Nướng lấy cảm hứng từ trái ổi xá lị – loại trái có nhiều nước, ít đường, ít hạt, ít tinh bột, vốn dĩ đã rất thích hợp dùng trong chế biến bánh ngọt. Cùng kết hợp với phúc bồn tử và sô-cô-la trắng đã tạo nên lớp mousse cân bằng về độ chua ngọt. \r\n\r\nBánh Mousse Ổi hồng & Chanh dây có hai lớp nhân được chế biến thủ công để giữ hương vị trái cây nguyên bản. Với lớp nhân từ quả ổi xá lị thì thịt ổi được cắt hạt lựu nên khi nhai cho cảm giác sần sật còn lớp nhân chanh dây mềm tươi mát. \r\n\r\nBánh Mousse Ổi hồng & Chanh dây đang là mẫu bánh mousse có nhiều lớp nhất tại Cái Lò Nướng.', 'tropicalVibesMousse.jpg', 3),
(12, 'Chéri Lady – Entremet Cherry', 595000, 'Ngọt dịu – Chua thanh – Thơm tự nhiên – Béo nhẹ.', 'Phần thân bánh gồm các lớp chính:\r\n\r\n+ Mousse cherry.\r\n\r\n+ Nhân cherry và rượu cherry.\r\n\r\n+ Nhân sô-cô-la tươi vị matcha.\r\n\r\n+ Bông lan vị vani.', 'Quả mâm xôi, jelly, sô-cô-la trắng phun xù, tráng gương.', 'Bánh nên được dùng trong ngày và ngon hơn khi bảo quản lạnh trước khi thưởng thức.', 'Entremet Cherry là mẫu bánh có thành phần cấu trúc hết sức cầu kỳ với nhiều tầng nhân được làm thủ công hết sức công phu. Bánh vừa có vị ngọt dịu vừa có vị chua thanh và hương thơm tự nhiên tinh tế.\r\n\r\nTrái cherry nhập khẩu cao cấp kết hợp sữa chua tạo thành lớp mousse đặc biệt mới lạ. Bánh có hai lớp nhân được làm từ cherry tươi kết hợp với một chút rượu cherry, lớp nhân còn lại có nguyên liệu chính từ sô-cô-la tươi vị matcha từ Nhật Bản và sô-cô-la trắng nguyên chất 40%. Lớp nhân sô-cô-la rất mềm dẻo và mang đậm hương vị matcha.\r\n\r\nĐể bánh cốt bánh bông lan vị vani là thành phần không thể thiếu để bánh luôn được thưởng thức trọn vẹn. Tại Cái Lò Nướng, bánh bông lan luôn mềm xốp và ngon lành. \r\n\r\nBánh Entremet Cherry là mẫu bánh có lớp trang trí cầu kỳ trong dòng bánh này, vì đây là sự kết hợp giữa kỹ thuật tráng gương và phun xù để làm cho bánh được bắt mắt và hấp dẫn hơn.', 'cheriLady.jpg', 4),
(13, 'Delicate Bloom – Bánh Kem Bắp Dâu', 465000, 'Ngọt dịu – Thơm đặc trưng – Béo nhẹ.', 'Phần thân bánh gồm các lớp chính:\r\n\r\n+ Mousse bắp.\r\n\r\n+ Bông lan bắp.', 'nho, dâu, đào, bắp.', 'Bánh nên được dùng trong ngày và ngon hơn khi bảo quản lạnh trước khi thưởng thức.', 'Delicate Bloom không chỉ là một phiên bản mới mẻ của hương vị bắp truyền thống mà còn là nỗ lực của Cái Lò Nướng trong việc không ngừng đổi mới sáng tạo, mang đến sức sống mới cho những vị bánh đã trở thành biểu tượng quen thuộc với khách hàng lâu năm. Bánh Kem Bắp Dâu mới với tạo hình đóa hoa nở rộ – “bloom” đem tới màu sắc rực rỡ của những ngày cuối xuân đầu hè ấm áp, tổng hòa của những hương vị thân quen, gần gũi.\r\n\r\nTạo hình bánh độc đáo với cánh hoa được tạo thành từ các loại trái cây như dâu, đào, bắp và nho.\r\nPhần mousse thơm ngon và bông lan êm dịu đều được làm từ những hạt bắp căng tròn tạo nên một hương vị đặc biệt và độc đáo.\r\nVới sự đổi mới trong trang trí, chúng mình muốn mang lại cho khách hàng trải nghiệm tốt nhất mỗi khi đặt bánh, mỗi chiếc bánh vượt qua kỳ vọng của bạn.\r\n\r\nBạn hãy đến và thưởng thức ngay Delicate Bloom vì đó là một sự kết hợp hoàn hảo giữa hương vị truyền thống và nghệ thuật sáng tạo hiện đại!', 'delicateBloom.jpg', 5),
(14, 'Flan Gato Berry Mix', 515000, 'Ngọt dịu – Béo nhẹ – Thơm – Đắng nhẹ.', 'Phần thân bánh gồm các lớp chính:\r\n\r\n+ Bánh flan vị truyền thống.\r\n\r\n+ Bông lan sô-cô-la.', 'jelly caramel, dâu tươi, việt quất.', 'Bánh nên được dùng trong ngày và ngon hơn khi bảo quản lạnh trước khi thưởng thức.', 'Flan Gato là dòng bánh mà Cái Lò Nướng chiếm ưu thế về sản lượng cung cấp cho thị trường Hồ Chí Minh. Bánh có hương vị ngon lành nên người dùng ở mọi lứa tuổi đều yêu thích.\r\n\r\nBánh có hai lớp chính, đó là flan truyền thống ngọt ngào mềm, căng mịn và bông lan sô-cô-la có vị đắng nhẹ tinh tế. Hai lớp bánh với hai hương vị khác nhau nhưng khi kết hợp tạo nên một chiếc bánh ngon nịnh vị và khi dùng thực khách không có cảm giác ngán.\r\n\r\nFlan Gato Berry Mix là mẫu bánh có phần trang trí từ dâu tươi và việt quất tươi mát nằm bên trên lớp jelly caramel. Một phụ kiện không thể thiếu trên chiếc bánh kem mà đặc biệt cực kỳ phù hợp với Flan Gato đó là bộ sưu tập cây ghim với nhiều chủ đề khác nhau.', 'flanGatoBerryMix.png', 6),
(15, 'Fruits and Nuts Biscotti – Biscotti trái cây và hạt', 59000, NULL, 'Hạnh nhân, hạt điều, nho khô, mứt hoa atiso, nam việt quất, lòng trắng, đường cát, bột mì.', NULL, NULL, 'Đánh dấu sự trở lại “NƠI TÌNH YÊU BẮT ĐẦU” và dịp “ra mắt” của cửa hàng Cái Lò Nướng tại Thủ Đức. Chúng mình đã mang đến món quà đặc biệt đến Fan của Cái Lò Nướng:\r\n\r\n6 Loại bánh khô với hương vị độc đáo, hứa hẹn làm hài lòng mọi khẩu vị.\r\n– Cookie rong biển hạt: Sự kết hợp hài hòa giữa rong biển, các loại hạt dinh dưỡng và vị ngọt thanh của cookie, mang đến trải nghiệm hoàn toàn mới.\r\n– Cookie chanh dây: Vị chua ngọt của chanh dây quyện cùng bánh quy bơ, tạo nên hương vị khó quên.\r\n– Cookie chà bông cay: Vị mặn mặn, cay cay kích thích cùng vị ngọt nhẹ của bánh quy, níu giữ bạn ngay từ miếng đầu tiên.\r\n– Cookie kem phô mai: Vị ngọt, béo, mặn hài hòa quyện cùng vị phô mai thơm lừng, mang đến trải nghiệm vị giác khó quên.\r\n– Biscotti Trái Cây và Hạt: Sự kết hợp độc đáo giữa nho khô, atiso và hạnh nhân mang đến hương vị thơm ngon, bổ dưỡng.\r\n– Snack rong biển: Vị giòn tan, đậm đà của rong biển hoà cùng vị mặn ngọt rất “cuốn” nhờ nước sốt tự nấu, kích thích vị giác.\r\nTất cả các loại bánh mới này đều được làm từ những nguyên liệu lành mạnh thân thiện với sức khỏe của bạn. Mỗi hộp bánh đều là món quà vặt nhâm nhi của bạn cùng những người thân yêu.', 'fruitsAndNutsBiscotti.jpg', 7),
(16, 'Bánh Mì Kem Phô mai Nam Việt Quất', 27000, NULL, NULL, NULL, NULL, 'Bánh Mì Kem Phô mai Nam Việt Quất: Bánh mì mềm, nhân phô mai và mứt nam việt quất.', 'banhMiKemPhoMaiVietQuat.jpg', 8),
(17, 'SWEETBOX LOVE – Hộp 8 vị', 295000, 'Ngọt dịu – Béo nhẹ – Chua ngọt – Thơm tự nhiên.', 'Lớp trang trí trái cây tươi, sô-cô-la hoặc jelly,…\r\nMousse theo từng vị bánh.\r\nCốt bánh bông lan.', NULL, 'Bánh nên được dùng trong ngày và ngon hơn khi bảo quản lạnh trước khi thưởng thức.', 'Sweetbox Love chính là lời chúc Valentine ý nghĩa mà Cái Lò Nướng dành riêng cho mùa yêu. Từng chi tiết, từ sắc hồng dịu dàng đến lớp ép kim tinh tế, đều thể hiện sự chăm chút và tinh thần lãng mạn của ngày lễ tình nhân.\r\nBên trong, 16 hương vị mousse không chỉ là món tráng miệng, mà còn là “cái cớ” để cả hai ngồi lại, chia sẻ những câu chuyện nhỏ trong ngày và cảm nhận sự hiện diện đầy ý nghĩa của nhau. Mỗi hương vị, mỗi câu chuyện… sẽ biến một buổi tối bình thường thành một kỷ niệm Valentine thật đáng nhớ.\r\n3 lựa chọn Sweetbox Love dành cho bạn mùa Valentine này:\r\nSet 8 bánh: Khế (vị mới), Cherry, Bơ, Bắp, Chuối Caramel, Mãng Cầu, Trà Xanh, Ổi Hồng.\r\nSet 12 bánh: Măng Cụt (vị mới), Cherry, Bơ, Bắp, Táo, Yuzu (Sữa Chua Phô Mai), Xoài, Lê Hoa Cúc, Dưa Lưới, Dừa, Trà Xanh, Ổi Hồng.\r\nSet 16 bánh: Măng Cụt, Khế, Cherry, Bơ, Bắp, Táo, Yuzu (Sữa Chua Phô Mai), Xoài, Lê Hoa Cúc, Chuối Caramel, Mãng Cầu, Dưa Lưới, Vải Hoa Hồng, Dừa, Trà Xanh, Ổi Hồng.\r\nValentine này, không cần phải rình rang. Chỉ cần một hộp Sweetbox Love, và nhiều thời gian bên nhau – thế là đủ cho một mùa yêu thật dịu dàng.', 'sweetBoxLove.jpg', 1),
(18, 'SWEETBOX LOVE – Hộp 8 vị', 295000, 'Ngọt dịu – Béo nhẹ – Chua ngọt – Thơm tự nhiên.', 'Lớp trang trí trái cây tươi, sô-cô-la hoặc jelly,…\r\nMousse theo từng vị bánh.\r\nCốt bánh bông lan.', NULL, 'Bánh nên được dùng trong ngày và ngon hơn khi bảo quản lạnh trước khi thưởng thức.', 'Sweetbox Love chính là lời chúc Valentine ý nghĩa mà Cái Lò Nướng dành riêng cho mùa yêu. Từng chi tiết, từ sắc hồng dịu dàng đến lớp ép kim tinh tế, đều thể hiện sự chăm chút và tinh thần lãng mạn của ngày lễ tình nhân.\r\nBên trong, 16 hương vị mousse không chỉ là món tráng miệng, mà còn là “cái cớ” để cả hai ngồi lại, chia sẻ những câu chuyện nhỏ trong ngày và cảm nhận sự hiện diện đầy ý nghĩa của nhau. Mỗi hương vị, mỗi câu chuyện… sẽ biến một buổi tối bình thường thành một kỷ niệm Valentine thật đáng nhớ.\r\n3 lựa chọn Sweetbox Love dành cho bạn mùa Valentine này:\r\nSet 8 bánh: Khế (vị mới), Cherry, Bơ, Bắp, Chuối Caramel, Mãng Cầu, Trà Xanh, Ổi Hồng.\r\nSet 12 bánh: Măng Cụt (vị mới), Cherry, Bơ, Bắp, Táo, Yuzu (Sữa Chua Phô Mai), Xoài, Lê Hoa Cúc, Dưa Lưới, Dừa, Trà Xanh, Ổi Hồng.\r\nSet 16 bánh: Măng Cụt, Khế, Cherry, Bơ, Bắp, Táo, Yuzu (Sữa Chua Phô Mai), Xoài, Lê Hoa Cúc, Chuối Caramel, Mãng Cầu, Dưa Lưới, Vải Hoa Hồng, Dừa, Trà Xanh, Ổi Hồng.\r\nValentine này, không cần phải rình rang. Chỉ cần một hộp Sweetbox Love, và nhiều thời gian bên nhau – thế là đủ cho một mùa yêu thật dịu dàng.', 'sweetBoxLove.jpg', 1);

--
-- Chỉ mục cho các bảng đã đổ
--

--
-- Chỉ mục cho bảng `product`
--
ALTER TABLE `product`
  ADD PRIMARY KEY (`id`),
  ADD KEY `type` (`category_id`) USING BTREE;

--
-- AUTO_INCREMENT cho các bảng đã đổ
--

--
-- AUTO_INCREMENT cho bảng `product`
--
ALTER TABLE `product`
  MODIFY `id` int NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=19;

--
-- Các ràng buộc cho các bảng đã đổ
--

--
-- Các ràng buộc cho bảng `product`
--
ALTER TABLE `product`
  ADD CONSTRAINT `FK1mtsbur82frn64de7balymq9s` FOREIGN KEY (`category_id`) REFERENCES `category` (`id`);
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
